# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Intact Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Intact Test

 pod 'Cosmos'
 pod 'Alamofire'

  target 'Intact TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Intact TestUITests' do
    # Pods for testing
  end

end
